#!/bin/bash
# use this for you user data (script from top to bottom)
# install httpd (Linux 2 version)
yum update -y
yum install httpd
systemctl start httpd
systemctl enable httpd
echo "<h1>Hello world from $(hostname -f)</h1>" > /var/www/index.html
